### ISSUE TITLE
 CreateProcess error=193, %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by himanshudwivedi** [code-smell/php-automate-build-ant#2]
Hi,

I am getting an error Build failed: CreateProcess error=193, %1 is not a valid Win32 application.

Can u please help?

regards,
Himanshu

**Comment by tbreuss** [comment]
Hi Himanshi
I have no clue what this error message means. It sounds like you are using Windows?! Since I have no Windows OS here where I could test this I'm not able to help you. Sorry!
Best regards,
Thomas
